version: '3.8'

services:
  mongodb:
    container_name: turkcell-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  kafka_data:
  mongodb_data: